### ISSUE TITLE
No such file

### ISSUE THREAD

**Issue by Fairywyt** [xuzf-git/WordSegment-and-PosTag#2]
FileNotFoundError: [Errno 2] No such file or directory: './data/PeopleDaily_Token_shortpath_result.txt'

**Comment by xuzf-git** [comment]
谢谢提醒，需要将[evaluate.py](https://github.com/xuzf-git/WordSegment-and-PosTag/blob/main/evaluate.py)中以下两行的文件名修改为一致 https://github.com/xuzf-git/WordSegment-and-PosTag/blob/f2a7c5cfc0bffabafaf088ecb4672401c88c8ac9/evaluate.py#L62
https://github.com/xuzf-git/WordSegment-and-PosTag/blob/f2a7c5cfc0bffabafaf088ecb4672401c88c8ac9/evaluate.py#L102
我已经在commit c3e4c30b1116f5c092ea4816f05e19f85aa1b2c9 中修改了该问题
