### ISSUE TITLE
数据处理部分报错

### ISSUE THREAD

**Issue by ShaoHLeon** [xuzf-git/WordSegment-and-PosTag#3]
修改如下（路径需要修改）：
with open('../data/PeopleDaily_clean.txt', 'r', encoding='utf8') as f:
    for line in f.readlines():
        line = line.strip().split() # 去除首尾空白字符，并按空白字符拆分成列表
        line_clean = []
        for w in line:
            line_clean.append(w[:-2])
        str1 = str1 + ' '.join(line_clean) + '\n'

with open('../data/PeopleDaily_Token.txt', 'w', encoding='utf8') as f:
    f.write(str1)

**Comment by xuzf-git** [comment]
在项目根目录下运行预处理程序，应该不会出现路径问题。
`cd /path/to/project/WordSegment-and-PosTag`
`python ./data/RemovePostag.py`
